import Mail1 from "./mails/mail1";
import Mail2 from "./mails/mail2";
import Mail3 from "./mails/mail3";
import Mail4 from "./mails/mail4";
import Mail5 from "./mails/mail5";
import Mail6 from "./mails/mail6";
import Mail7 from "./mails/mail7";
import Mail8 from "./mails/mail8";

const Inbox = [
  {
    mail: Mail1,
    id: 1,
    title: "Check 24 Angebot",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "someemail@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "H",
  },
  {
    mail: Mail2,
    id: 2,
    title: "Peter Hansa - Küchenreperatur",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "Thomas Köllner",
    date: "16.10.2013 19:12",
    subject: "Something else",
    capital: "B",
  },
  {
    mail: Mail3,
    id: 3,
    title: "Das ist ein langer titel",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "Office365@company.com",
    date: "23.06.2019 10:30",
    subject: "Microsoft account security alert",
    capital: "W",
  },
  {
    mail: Mail4,
    id: 4,
    title: "Email 4",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "itdeskservice@itssc.com",
    date: " 13.12.2018 07:41",
    subject: " IT Service Support",
    capital: "B",
  },
  {
    mail: Mail5,
    id: 5,
    title: "Email 5",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "mailbox@weboutlk.com",
    date: "23.11.2018 11:01",
    subject: "Deine Mailbox ist fast voll.",
    capital: "M",
  },
  {
    mail: Mail6,
    id: 6,
    title: "Email 6",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "mailadmin@helpdesking",
    date: "09.11.2018 13:34",
    subject: "Dear User",
    capital: "D",
  },
  {
    mail: Mail7,
    id: 7,
    title: "Email 7",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "08.11.2018 11:30 Uhr",
    subject: "Warnung Mitarbeiter !!",
    capital: "W",
  },
  {
    mail: Mail8,
    id: 8,
    title: "Email 8",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "xy@yxyasdjkkaj.com",
    date: "23.09.2029 19:12",
    subject: "Das ist ein Test",
    capital: "Y",
  },
  {
    mail: Mail3,
    id: 9,
    title: "Email 9",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "X",
  },
  {
    mail: Mail1,
    id: 10,
    title: "Email 10",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "H",
  },
  {
    mail: Mail2,
    id: 11,
    title: "Email 11",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "H",
  },
  {
    mail: Mail3,
    id: 12,
    title: "Email 12",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "H",
  },
  {
    mail: Mail2,
    id: 13,
    title: "Email 11",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "H",
  },
  {
    mail: Mail3,
    id: 14,
    title: "Email 12",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "A",
  },
  {
    mail: Mail2,
    id: 15,
    title: "Email 11",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "C",
  },
  {
    mail: Mail3,
    id: 16,
    title: "Email 12",
    type: "AllInbox",
    response: "",
    conversation: [],
    sender: "win@domain.com",
    date: "23.09.2029 19:12",
    subject: "Relog - Windows",
    capital: "D",
  },
];

export default Inbox;
