import Mail1 from "./mails/mail1";
import Mail2 from "./mails/mail2";
import Mail3 from "./mails/mail3";

const Inbox = [
  {
    mail: Mail1,
    id: 1,
    title: "Check 24 Angebot",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail2,
    id: 2,
    title: "Peter Hansa - Küchenreperatur",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail3,
    id: 3,
    title: "Das ist ein langer titel",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail1,
    id: 4,
    title: "Email 4",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail2,
    id: 5,
    title: "Email 5",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail3,
    id: 6,
    title: "Email 6",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail1,
    id: 7,
    title: "Email 7",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail2,
    id: 8,
    title: "Email 8",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail3,
    id: 9,
    title: "Email 9",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail1,
    id: 10,
    title: "Email 10",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail2,
    id: 11,
    title: "Email 11",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail3,
    id: 12,
    title: "Email 12",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail2,
    id: 13,
    title: "Email 11",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail3,
    id: 14,
    title: "Email 12",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail2,
    id: 15,
    title: "Email 11",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
  {
    mail: Mail3,
    id: 16,
    title: "Email 12",
    type: "AllInbox",
    response: "",
    conversation: [],
  },
];

export default Inbox;
